### ISSUE TITLE
Need a way to handle files with transient columns

### ISSUE THREAD

**Issue by seajhawk** [MeltanoLabs/tap-csv#45]
I've already shared this in the #windows slack channel, but I want to make sure that my use case isn't lost.

The files I'm loading have about 20% of the columns that come and go. 

If I load one file with one set of columns, then another file that has a new column into the same table the new column is ignored `[info     ] time=2022-07-19 16:35:06 name=tap-csv level=WARNING message=Property 'Column Name (2021))' was present in the 'table_meltano' stream but not found in catalog schema. Ignoring.`. 

In a loader I wrote before trying Meltano, I handled the transient columns (20% of the columns) by using Pandas and combining them into a single json column in the dataframe before loading. Then I use dbt to run some SQL that extracts that data back out into its own, properly designed table for reporting.

I think I could figure out how to create my own tap-csv to implement my method of handling the transient columns, but I've probably spent much longer working on ELT than I should and need to move on to the phase of my project where I'm setting up Superset, Hex, and perhaps Lightdash so others can start exploring the data.

**Comment by pnadolny13** [comment]
@seajhawk I dont think this is something that the tap would handle because it does support a fluctuation of columns on each sync if you send a different catalog file each time, so I'm going to close the issue.

Maybe you could handle it with how you call Meltano but is there a way to not fluctuate columns? It seems like a data problem that would ideally be fixed in the source but I know its out of your control sometimes.

I'd double check this via the docs and slack community but I think youre catalog file is being re-used, if you did a full sync and used a new catalog each time you might be able to get away with it (depending on the target). I think if you run with the `--full-refresh` argument you'd get a new catalog file for each run. Hope that help!

**Comment by seajhawk** [comment]
@pnadolny13 - Thanks for reviewing this!

I agree that this doesn't seem like the job of the general use tap-csv plugin (unless lots of people need this capability), because it's moving beyond the primitive capability that most reasonable people would expect.

I'm not familiar with sending a catalog file, but if I do that and this tap is feeding to a target like target-postgres, will the target be able to handle the change in the catalog file? (am I thinking about this correctly?) I'm guessing it may not unless it has an additive mode where it can add new columns, but not remove columns that are not in the new catalog. 

I was chatting with Douwe last week and he suggested there is a way to run some arbitrary code between the tap and target via a custom mapper. I need to look into this further as time permits.

**Comment by pnadolny13** [comment]
>I'm not familiar with sending a catalog file, but if I do that and this tap is feeding to a target like target-postgres, will the target be able to handle the change in the catalog file? (am I thinking about this correctly?) I'm guessing it may not unless it has an additive mode where it can add new columns, but not remove columns that are not in the new catalog.

>I was chatting with Douwe last week and he suggested there is a way to run some arbitrary code between the tap and target via a custom mapper. I need to look into this further as time permits.

@seajhawk yeah those are good questions! I'm not sure the answers though 😄 , I'd follow up in slack and others can help. Sounds like mappers might be able to do the job though.
