### ISSUE TITLE
Default to `utf-8` encoding

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-csv#69]
Slack thread https://meltano.slack.com/archives/C01TCRBBJD7/p1665147787434089

OG issue https://github.com/MeltanoLabs/tap-csv/issues/44

**Comment by pnadolny13** [comment]
@visch thanks for opening this!

TIL that [open()](https://docs.python.org/3/library/functions.html#open) uses your machine's preferred encoding. I was expecting it to be something consistent under the hood but I see why this can be confusing because I think running the tap on the same file with same configs on two different machines could produce different outputs.

> encoding is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever [locale.getpreferredencoding()](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) returns), but any [text encoding](https://docs.python.org/3/glossary.html#term-text-encoding) supported by Python can be used. See the [codecs](https://docs.python.org/3/library/codecs.html#module-codecs) module for the list of supported encodings.

After learning that I'd agree that choosing a default for ourselves in the tap is a good idea. But I'm not all that versed in this stuff, especially cross platform compatibility, so I'd like to hear others opinions.

**Comment by edgarrmondragon** [comment]
UTF-8 would be a sane default. Users could still let Python use the system's encoding by configuring `"encoding": null` for each file.

**Comment by aaronsteers** [comment]
Agreed with making `utf-8` the default. I don't think there's a strong need to require system-specific encoding, but @edgarrmondragon's suggestion of passing an explicit `null` value would make sense to me. (More likely though we'd recommend them to send `latin1` or another explicit encoding name.)
