### ISSUE TITLE
 INFO:tap-csv:Skipping deselected stream 'payers'.

### ISSUE THREAD

**Issue by zairiedu** [MeltanoLabs/tap-csv#97]
Hi!
I used the **files:** configuration first in meltano to load one file 'patients.csv', and all was good.
Then I used the **csv_files_definition:** to load two files 'payors.csv' and 'patients.csv.
but then it gave me this message:
```
$ meltano run tap-csv target-postgres
2022-12-29T19:07:04.462545Z [warning  ] Failed to create symlink to 'meltano.exe': administrator privilege required
2022-12-29T19:07:04.593348Z [info     ] Environment 'dev' is active
2022-12-29T19:07:07.404553Z [info     ] INFO:tap-csv:Skipping deselected stream 'payers'. cmd_type=elb consumer=False name=tap-csv producer=True stdio=stderr string_id=tap-csv
2022-12-29T19:07:07.490515Z [info     ] Block run completed.           block_type=ExtractLoadBlocks err=None set_number=0 success=True
```
I checked this directory in meltano 
**run>.meltano>run>tap-csv>state,json:**
```
{
  "bookmarks": {
    "patients": {}
  }
}
```

Not sure where to make it select whatever in the csv_definition.json file:
```
[
    {
      "entity": "patients",
      "path": "./extract/synthea/patients.csv",
      "keys": ["Id"],
      "encoding": "UTF-8"
    },
    {
      "entity": "payers",
      "path": "./extract/synthea/payers.csv",
      "keys": ["Id"],
      "encoding": "UTF-8"
    }

  ]
```
any ideas ?

**Comment by zairiedu** [comment]
This is probably not the most elegant way to resolve this but my workaround was to delete the 
**run>.meltano>run>tap-csv**  directory.
and then add the tap_csv extractor again.
and it seems to take all the files in csv_definition.json

**Comment by pnadolny13** [comment]
Hey @zairiedu! I think this is related to [a bug in Meltano](https://github.com/meltano/meltano/issues/6763) itself. The catalog file doesn't get invalidated properly. Also see https://github.com/meltano/meltano/issues/6919 with a couple other feature ideas that would make this easier. Feel free to add comments to those threads.

I'm going to close this issue for now since it sounds like its resolved and the discussions can go in the meltano issues but feel free to re-open if you think there still something tap related!
